### ISSUE TITLE
gexport error: unlink results in no such file or directory

### ISSUE THREAD

**Issue by thowo** [Cacti/plugin_gexport#47] opened 2021-01-11 16:06 UTC
Hello Cacti Developer,

I have an issue with the gexport plugin. From time to time it reports the following error in cacti.log:

CMDPHP PHP ERROR WARNING Backtrace: (/plugins/gexport/poller_export.php[105]:export_graph_start_task(), /plugins/gexport/functions.php[938]:export_graph_files(), /plugins/gexport/functions.php[966]:check_remove(), /plugins/gexport/functions.php[2102]:unlink(), CactiErrorHandler())

2021/01/11 16:57:05 - ERROR PHP WARNING in Plugin 'gexport': unlink(/tmp/cacti-rsync-temp-1/graph_9036.html): No such file or directory in file: /opt/cacti/cacti-1.2.10/plugins/gexport/functions.php on line: 2102

But the file in question exists:

 ls -la /tmp/cacti-rsync-temp-1/graph_9036.html
-rw-r--r-- 1 cacti cacti 804 Jan 11 16:57 /tmp/cacti-rsync-temp-1/graph_9036.html

I am using cacti 1.2.10 with gexport plugin version 1.4.2 on a debian 10.7 system.
Export Command Arguments is:  rsync -zav

thanks in advance,
best regards,

Tom

**Comment by netniV** [comment] 2021-01-13 21:00
So, this may be an issue between systemd and the os, interfering.  Basically anything that normally goes to /tmp may be redirected to a special systemd folder under Ubuntu/Debian.  This is why rconfig uses directories under its own plugin area to handle the downloads and prevent this type of error.

Can you confirm you OS version, and whether you run cacti under apache or something else?

**Comment by thowo** [comment] 2021-01-14 08:18
Hi, thanks for your reply. You are right, I am running cacti under apache  2.4.38-3+deb10u4 and my OS Version is 10.7. 
I will give it a try to export to a different directory within the regular filesystem and report back.

Many Thanks,
best regards,
cheers,

Tom

**Comment by thowo** [comment] 2021-01-14 10:17
Hi,
bad news, I changed to /opt/cacti/exportdirectory (which is a local ext 4 fs on LVM Volume) and same error came up. I have 3 exports running and it seems if they overlap in time the error happens. Any thoughts on this?
thanks in advance,
best regards,
Tom

**Comment by netniV** [comment] 2021-05-20 08:37
I would use separate temporary areas but I'm not sure if that is configurable within the gexport options without going to have a look.  The alterantive would be to update the TMP location as I doubt the path is actually hardcoded since not all systems may have a /tmp/

**Comment by TheWitness** [comment] 2022-12-03 16:01
I've confirmed some bad behavior this morning with Tree Export method.

**Comment by TheWitness** [comment] 2023-03-13 22:32
Closing this one.  I can not reproduce with the latest develop.

**Closed by TheWitness** 2023-03-13 22:32 UTC
Labels: bug, confirmed
